# GRPC server settings
grpc:
    host: 0.0.0.0
    port: 50051

# HTTP server setting
http:
    host: 0.0.0.0
    port: 8080
    is_https: false # Enable HTTPS
    https:
        cert_file: cert/serverCert.pem
        key_file: cert/serverKey.pem

inmemory: false

# database settings
db:
    host: postgres
    port: 5432
    user: event-db
    password: event-db
    name: event-db

# logging settings
logger:
    filepath: /var/log/calendar/log.json
    level: debug # debug, info, warn, error

# metric settings
metrics:
    enable: true
    host: otel_collector
    port: 4317

# JWT auth
auth:
    secret_key: PNvEBrLW+zU7SPi+nqmY5KD6FVecuQW1VHFRUI8xAGKM4JnIvR3zQescAq
    token_validity_period: 15	# in minutes
