# queue settings
queue:
    host: rabbitmq
    port: 5672
    user_name: guest
    password: guest
    name: event-queue

# database settings
db:
    host: postgres
    port: 5432
    user: calendar-user
    password: calendar-user
    name: calendar-db

# logging settings
logger:
    filepath:
    level: debug # debug, info, warn, error

# database scan period in minutes
schedule_period: 30
